id: nictiz.fhir.nl.r4.acutezorg
canonical: http://nictiz.nl/fhir
name: AcuteZorg
title: "Acute Zorg"
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2026+
releaseLabel: ci-build
publisher:
  name: Nictiz
description: "FHIR R4 Implementation Guide for information exchange in acute care settings in the Netherlands (Acute Zorg), built on nl-core. The first use case is the Ambulanceverwijzing naar HAP (ambulance to GP out-of-hours post, AMB naar HAP)."
menu:
  Home: index.html
  Functional Design: functional-design.html
  Data Model: data-model.html
  Data Exchange: data-exchange.html
dependencies:
  nictiz.fhir.nl.r4.nl-core: 0.12.0-beta.4
  nictiz.fhir.nl.r4.zib2020: 0.12.0-beta.4
  hl7.fhir.uv.tools.r4: 1.1.2
FSHOnly: false
applyExtensionMetadataToRoot: false
parameters:
  show-inherited-invariants: false
